services:
  cdn:
    image: nginx:latest
    container_name: cdn
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cdn.conf:/etc/nginx/conf.d/default.conf
      # - ./ssl:/etc/ssl/certs
    # networks:
    #   - cdn_network